### ISSUE TITLE
Python integer division example [TWP40]

### ISSUE THREAD

**Issue by reingart** [PyAr/PyZombis#211] opened 2022-03-19 01:29 UTC
The lecture has a C example
http://pyar.github.io/PyZombis/master/lectures/TWP40/TWP40_12.html

Ad an example in python with `//`
See https://docs.python.org/3/library/stdtypes.html#numeric-types-int-float-complex 

Add E2E Playwright test

**Comment by sujith-rek** [comment] 2023-02-27 08:42
Hey,
I'd like to work on this
please assign it to me

**Comment by sitamgithub-MSIT** [comment] 2023-03-06 13:42
If the issue is still not resolved, I'd like to work on this
please assign it to me

**Closed** 2024-03-12 13:09 UTC
Labels: enhancement, good first issue
